### ISSUE TITLE
Anteproyecto

### ISSUE THREAD

**Issue by PedroGarcia11439** [SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-1#1]
[Anteproyecto Idea Cafe.docx](https://github.com/SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-1/files/9698757/Anteproyecto.Idea.Cafe.docx)

**Comment by josealfredo79** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
